name: Issue Automatically

on:
  push:
    branches:
      - 'main'
      - 'feature/*'

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest commit message
        id: get_commit
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          CLEAN_MSG=$(echo "$COMMIT_MSG" | xargs)
          echo "issue_title=$CLEAN_MSG" >> $GITHUB_OUTPUT

      - name: Create GitHub issue
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          TITLE="${{ steps.get_commit.outputs.issue_title }}"

          curl -i -X POST \
               -H "Authorization: Bearer $MY_GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               -d "{\"title\":\"$TITLE\"}" \
               "https://api.github.com/repos/${{ github.repository }}/issues"

